from pathlib import Path
import re

FILES = [
    Path("src/App.tsx"),
    Path("src/AlmPositionsPanel.tsx"),
    Path("src/demo-data.ts"),
    Path("README.md"),
]

REPLACEMENTS = {
    # Locale
    '"tr-TR"': '"en-GB"',

    # Dataset labels / importer
    '"Borçlar"': '"Payables"',
    '"Alacaklar"': '"Receivables"',
    '"Finansal Borç"': '"Financial Debt"',
    '"Hazır"': '"Ready"',
    '"Analiz ediliyor…"': '"Analyzing…"',
    '"CSV seç veya buraya bırak"': '"Choose a CSV or drop it here"',
    '} satır': '} rows',
    '} otomatik eşleşme': '} auto-matched',
    '} eşleşmeyen': '} unmatched',
    '} kalite bulgusu': '} quality findings',
    'Mutabakat: ': 'Reconciliation: ',
    'Eşleştirme tablosu': 'Mapping table',
    '<th>Kaynak</th>': '<th>Source</th>',
    '<th>Güven</th>': '<th>Confidence</th>',
    '<th>Durum</th>': '<th>Status</th>',
    '"Eşleşmedi"': '"Unmatched"',
    'SAP uyumlu CSV eşleştirme, kalite kontrolü ve mutabakat': 'SAP-compatible CSV mapping, data-quality checks, and reconciliation',
    ' güncel veri seti': ' current datasets',
    'Güncel dönem': 'Current period',
    'Analizde kullanılacak dosyalar': 'Files used in the analysis',
    'Önceki dönem dosyalarını ekle': 'Add previous-period files',
    'What Changed için opsiyonel': 'Optional for What Changed',
    'Para birimi': 'Currency',
    'Rapor tarihi': 'As-of date',
    'Açılış nakdi (mn)': 'Opening cash (mn)',
    'Kullanılabilir limit (mn)': 'Available facilities (mn)',
    'Politika tamponu (mn)': 'Policy buffer (mn)',
    'Demo veriyi yükle': 'Load demo data',
    'Örnek CSV’lerle çalıştır': 'Run with sample CSVs',
    'Analiz hazırlanıyor…': 'Preparing analysis…',
    'CFO analizini çalıştır': 'Run CFO analysis',

    # Data status
    'Veri &amp; Girdiler': 'Data &amp; Inputs',
    'Analiz kapsamını ve manuel pozisyonları yönetin': 'Manage analysis scope and manual positions',
    ' Manuel Pozisyon': ' Manual Positions',
    ' veri seti güncel': ' datasets ready',
    'Girdileri Kapat': 'Close Inputs',
    'Dosyaları Güncelle': 'Update Files',

    # Stress / gap drivers
    'Base, Moderate ve Severe stres senaryoları likidite eğrisi. Bir tarih seçmek için grafiğe tıklayın.': 'Liquidity curves for the Base, Moderate, and Severe stress scenarios. Click the chart to select a date.',
    '<th>Senaryo</th>': '<th>Scenario</th>',
    '<th>Min. nakit</th>': '<th>Min. cash</th>',
    '<th>Fonlama ihtiyacı</th>': '<th>Funding need</th>',
    '<th>Tampon ihlal günü</th>': '<th>Buffer breach days</th>',
    '<th>İlk ihlal</th>': '<th>First breach</th>',
    '} gün</td>': '} days</td>',
    '{ label: "Açılış"': '{ label: "Opening"',
    '{ label: "Tahsilatlar"': '{ label: "Receivables"',
    '{ label: "Ödemeler"': '{ label: "Payments"',
    '{ label: "Borç servisi"': '{ label: "Debt service"',
    '{ label: "Kapanış"': '{ label: "Closing"',
    'Seçili gün analizi': 'Selected-day analysis',
    ' tarihinde nakdi hareket ettiren unsurlar': ' cash-flow drivers',
    'İlk 3 yoğunlaşma': 'Top 3 concentration',
    'Günlük nakit köprüsü': 'Daily cash bridge',
    'Karşı taraf yoğunlaşması': 'Counterparty concentration',
    ' net etki': ' net impact',
    ' nakit hareketini göster': ' cash flows',
    '<th>Karşı taraf</th>': '<th>Counterparty</th>',
    '<th>Belge</th>': '<th>Document</th>',
    '<th>Yön</th>': '<th>Direction</th>',
    '<th>Etki</th>': '<th>Impact</th>',
    '"Giriş"': '"Inflow"',
    '"Çıkış"': '"Outflow"',

    # Maturity gap
    'Vade kovalarına göre varlık, yükümlülük ve kümülatif gap grafiği': 'Assets, liabilities, and cumulative gap by maturity bucket',
    'Kullanılabilir limitlerden sonra ': 'After available committed facilities, ',
    ' karşılanmamış 12 aylık fonlama ihtiyacı kalıyor.': ' of 12-month funding need remains uncovered.',
    'Taahhütlü limitler, 12 aylık minimum kümülatif açığı tamamen karşılıyor.': 'Committed facilities fully cover the minimum 12-month cumulative gap.',
    '12 aylık sözleşmesel görünüm': '12-month contractual view',
    'Alacak, ticari borç, borç servisi ve kullanılan kredi vadelerinin aynı merdivende karşılaştırılması': 'Receivables, payables, debt service, and drawn facilities compared on a single maturity ladder',
    'Varlık': 'Assets',
    'Yükümlülük': 'Liabilities',
    'Kümülatif gap': 'Cumulative gap',
    '12A sözleşmesel varlık': '12M contractual assets',
    '12A sözleşmesel yükümlülük': '12M contractual liabilities',
    'Minimum kümülatif gap': 'Minimum cumulative gap',
    '"Açılış"': '"Opening"',
    'Limit sonrası açık': 'Residual funding gap',
    'Fonlama aksiyonu gerekli': 'Funding action required',
    'Limit kapsamı yeterli': 'Facility coverage sufficient',
    '<th>Vade kovası</th>': '<th>Maturity bucket</th>',
    '<th>Başlangıç</th>': '<th>Start</th>',
    '<th>Bitiş</th>': '<th>End</th>',
    '<th>Varlık</th>': '<th>Assets</th>',
    '<th>Yükümlülük</th>': '<th>Liabilities</th>',
    '<th>Net gap</th>': '<th>Net gap</th>',
    '<th>Kümülatif gap</th>': '<th>Cumulative gap</th>',
    '} hareket</small>': '} flows</small>',
    ' kayıt eksik vade/tutar, para birimi farkı veya mükerrer borç referansı nedeniyle maturity gap dışında bırakıldı.': ' records were excluded from the maturity gap because of missing maturity/amount data, currency mismatch, or duplicate debt references.',

    # Debt & funding
    '36 aylık borç vade duvarı': '36-month debt maturity wall',
    '36 aylık finansman görünümü': '36-month funding view',
    'Borç vade duvarı, refinansman kapasitesi ve lender yoğunlaşması': 'Debt maturity wall, refinancing capacity, and lender concentration',
    'İlk 3 lender': 'Top 3 lenders',
    'Toplam finansal borç': 'Total financial debt',
    '12A vadesi gelen': 'Debt due in 12M',
    '12A refinansman açığı': '12M refinancing gap',
    'Kullanılabilir limit': 'Available facilities',
    'Limit kullanım oranı': 'Facility utilization',
    'En büyük vade duvarı': 'Largest maturity wall',
    'Refinansman planı gerekli': 'Refinancing plan required',
    'Mevcut limit kapasitesi yeterli': 'Available facility capacity is sufficient',
    'Önümüzdeki 12 ayda kullanılabilir limitlerden sonra ': 'Over the next 12 months, ',
    ' açık kalıyor.': ' remains uncovered after available facilities.',
    'Kullanılabilir taahhütlü limitler 12 aylık borç vadelerini karşılıyor.': 'Available committed facilities cover debt maturities over the next 12 months.',
    'Üç aylık borç vade duvarı': 'Quarterly debt maturity wall',
    'Lender yoğunlaşması': 'Lender concentration',
    ' borç · ': ' debt · ',
    ' boş limit': ' available facilities',
    '<th>Finansal borç</th>': '<th>Financial debt</th>',
    '<th>Taahhütlü limit</th>': '<th>Committed facilities</th>',
    '<th>Kullanılan limit</th>': '<th>Drawn facilities</th>',
    '<th>Boş limit</th>': '<th>Available facilities</th>',
    '<th>Finansman payı</th>': '<th>Funding share</th>',
    ' borç · {lender.facilityCount} limit': ' debt instruments · {lender.facilityCount} facilities',
    ' borç/limit kaydı eksik vade, eksik anapara, para birimi farkı veya mükerrer referans nedeniyle tamamen ya da vade duvarından hariç tutuldu.': ' debt/facility records were excluded fully or from the maturity wall because of missing maturity, missing principal, currency mismatch, or duplicate references.',

    # Interest rate risk
    'Faiz verisi tamamlanmalı': 'Interest-rate data incomplete',
    'Portföyün %': 'Interest rates are available for %',
    ' kısmında faiz oranı mevcut; eksik faiz tipi veya oranı duyarlılık sonucunu sınırlıyor.': ' of the portfolio; missing rate type or rate data limits the sensitivity analysis.',
    'Faiz riski yüksek': 'Elevated interest-rate risk',
    'Borç portföyünün %': '%',
    ' kısmı önümüzdeki 12 ayda değişken faize veya refinansmana açık.': ' of the debt portfolio is exposed to floating rates or refinancing over the next 12 months.',
    'Faiz riski kontrollü': 'Interest-rate risk controlled',
    '12 aylık yeniden fiyatlama riski toplam borcun %': '12-month repricing exposure represents %',
    ' seviyesinde.': ' of total debt.',
    '12 aylık yeniden fiyatlama görünümü': '12-month repricing view',
    'Sabit/değişken borç karması, refinansman riski ve yıllıklandırılmış faiz şoku etkisi': 'Fixed/floating debt mix, refinancing exposure, and annualized rate-shock impact',
    'Faiz veri kapsamı': 'Rate-data coverage',
    'Faiz taşıyan borç': 'Interest-bearing debt',
    'Değişken faizli borç': 'Floating-rate debt',
    ' portföy payı': ' portfolio share',
    'Ağırlıklı ort. faiz': 'Weighted average rate',
    'Oranı bilinen borç': 'Debt with known rate',
    'Yıllık faiz gideri': 'Annual interest expense',
    'Borç faiz karması': 'Debt-rate mix',
    'Sabit': 'Fixed',
    'Değişken': 'Floating',
    'Sınıflanmamış': 'Unclassified',
    'Repricing merdiveni': 'Repricing ladder',
    'Değişken faiz': 'Floating rate',
    'Sabit borç refinansmanı': 'Fixed-debt refinancing',
    'Faiz şoku duyarlılığı': 'Rate-shock sensitivity',
    '12 aylık repricing exposure için yıllıklandırılmış run-rate etki': 'Annualized run-rate impact on 12-month repricing exposure',
    'yıllık ek faiz gideri': 'additional annual interest expense',
    'şok sonrası gider': 'post-shock expense',
    'Değişken faiz riski': 'Floating-rate exposure',
    '12A sabit refinansman': '12M fixed-rate refinancing',
    '<th>Toplam borç</th>': '<th>Total debt</th>',
    '<th>Sabit</th>': '<th>Fixed</th>',
    '<th>Değişken</th>': '<th>Floating</th>',
    '<th>Yıllık faiz gideri</th>': '<th>Annual interest expense</th>',
    '<th>Veri kapsamı</th>': '<th>Data coverage</th>',
    ' enstrüman</small>': ' instruments</small>',
    ' faiz veri bulgusu var: eksik tip/oran/vade, para birimi farkı veya mükerrer borç referansı duyarlılık kapsamını etkiliyor.': ' rate-data findings remain: missing type/rate/maturity, currency mismatch, or duplicate debt references affect sensitivity coverage.',

    # Funding plan
    'Vadeli finansman sağla': 'Raise term funding',
    'Taahhütlü limitleri rezerve et': 'Reserve committed facilities',
    'Vade duvarını refinanse et': 'Refinance maturity wall',
    'Lender tabanını çeşitlendir': 'Diversify lender base',
    'Politika tamponunu korumak için limit dışı finansmanı kesinleştir.': 'Secure external funding to protect the policy buffer.',
    'Planlanan dönem için kullanılabilir limit kapasitesini ayır.': 'Reserve available facility capacity for the planned period.',
    'Yoğun vade döneminden önce borç yenileme görüşmelerini tamamla.': 'Complete refinancing discussions before the concentrated maturity period.',
    'İlk üç lender yoğunluğunu alternatif kapasiteyle azalt.': 'Reduce top-three lender concentration with alternative capacity.',
    'Dış finansman aksiyonu gerekli': 'External funding action required',
    ' limit kullanımından sonra ': ' after planned facility drawings, ',
    ' ek finansman gerekiyor.': ' of additional funding is required.',
    'Taahhütlü limit rezervasyonu gerekli': 'Committed facility reservation required',
    ' kullanılabilir limit rezerve edilirse politika tamponu korunuyor.': ' of available facilities is reserved, the policy buffer is maintained.',
    'Fonlama planı dengeli': 'Funding plan balanced',
    'Sözleşmesel nakit akışları politika tamponunu ek fonlama olmadan koruyor.': 'Contractual cash flows preserve the policy buffer without additional funding.',
    '12 aylık aksiyon planı': '12-month action plan',
    'Sözleşmesel likidite açığının taahhütlü limit ve dış finansmanla hangi dönemde kapatılacağı': 'Timing of committed-facility drawings and external funding required to close contractual liquidity gaps',
    '"Fonlanmış"': '"Funded"',
    '"Limit kullanımı"': '"Facility draw"',
    '"Dış finansman"': '"External funding"',
    'Toplam fonlama ihtiyacı': 'Total funding requirement',
    'Planlanan limit kullanımı': 'Planned facility draw',
    'Dış finansman ihtiyacı': 'External funding need',
    'İlk aksiyon tarihi': 'First action date',
    '"Aksiyon yok"': '"No action"',
    'Önerilen aksiyonlar': 'Recommended actions',
    ' tarihine kadar': ' by',
    'Yönetim planlama döneminde': 'During the management planning period',
    'Açık fonlama aksiyonu bulunmuyor.': 'No open funding actions.',
    '<th>Dönem</th>': '<th>Period</th>',
    '<th>Sözleşmesel likidite</th>': '<th>Contractual liquidity</th>',
    '<th>Yeni limit kullanımı</th>': '<th>New facility draw</th>',
    '<th>Yeni dış finansman</th>': '<th>New external funding</th>',
    '<th>Plan sonrası likidite</th>': '<th>Post-plan liquidity</th>',
    '<th>Kalan limit</th>': '<th>Remaining facilities</th>',

    # Policy limits
    'Likidite tamponu': 'Liquidity buffer',
    'Limit kullanımı': 'Facility utilization',
    'Değişken faiz payı': 'Floating-rate share',
    '12A refinansman kapsamı': '12M refinancing coverage',
    'Nakit koruma ve limit rezervasyonu planını devreye al.': 'Activate the cash-protection and facility-reservation plan.',
    'Yeni taahhütlü kapasite ekle veya kullanımı azalt.': 'Add committed capacity or reduce utilization.',
    'Alternatif lender kapasitesi oluştur.': 'Build alternative lender capacity.',
    'Yeni fonlamada sabit faiz payını artır.': 'Increase the fixed-rate share of new funding.',
    'Vadesi gelen borç için refinansman kapasitesini kesinleştir.': 'Secure refinancing capacity for maturing debt.',
    'İlk ihtiyaç tarihinden önce vadeli fonlama onayı al.': 'Obtain term-funding approval before the first funding-need date.',
    'ALCO risk iştahı': 'ALCO risk appetite',
    'Mevcut ALM verisiyle ölçülebilen likidite, fonlama, yoğunlaşma ve faiz limitleri': 'Liquidity, funding, concentration, and rate limits measurable from the current ALM dataset',
    '"Limitler içinde"': '"Within limits"',
    '"Yakın izleme"': '"Watch"',
    ' limit ihlali': ' limit breaches',
    'Toplam kontrol': 'Total checks',
    'Limit içinde': 'Within limits',
    'Yakın izleme': 'Watch',
    'Limit ihlali': 'Limit breaches',
    '<th>Politika limiti</th>': '<th>Policy limit</th>',
    '<th>Gerçekleşen</th>': '<th>Actual</th>',
    '<th>Yönetim aksiyonu</th>': '<th>Management action</th>',
    ' puan': ' pts',
    '"Uygun"': '"Pass"',
    '"İzle"': '"Watch"',
    '"İhlal"': '"Breach"',
    '"Aksiyon gerekmiyor."': '"No action required."',
    "Net Borç/FAVÖK ve faiz karşılama gibi finansal covenant'lar, bilanço ve gelir tablosu verisi bağlandığında bu kapsama eklenecek.": 'Financial covenants such as Net Debt/EBITDA and interest coverage can be added once balance-sheet and income-statement data are connected.',

    # What Changed
    'Dönem karşılaştırması': 'Period comparison',
    'Önceki yükleme ile güncel veri arasındaki likidite hareketleri': 'Liquidity movements between the previous and current datasets',
    '"Hareket mutabık"': '"Movement reconciled"',
    '"Açıklanamayan hareket"': '"Unexplained movement"',
    'Karşılaştırma için önceki dönem gerekli': 'Previous period required for comparison',
    'Importer içinden önceki dönem CSV’lerini ekleyerek tarih, tutar, yeni ve kaldırılan kayıt etkilerini görün.': 'Add previous-period CSVs in the importer to identify date shifts, amount changes, new items, and removed items.',
    'Tutar değişikliği': 'Amount changes',
    'Tarih kayması': 'Date shifts',
    'Yeni kayıt': 'New items',
    'Kaldırılan': 'Removed items',
    'Toplam likidite etkisi': 'Total liquidity impact',
    'Forecast hareketi': 'Forecast movement',
    'Tanımlanan sürücüler': 'Identified drivers',
    'Açıklanamayan': 'Unexplained',
    '<th>Değişiklik</th>': '<th>Change</th>',
    '<th>Karşı taraf / belge</th>': '<th>Counterparty / document</th>',
    '<th>Önceki</th>': '<th>Previous</th>',
    '<th>Güncel</th>': '<th>Current</th>',
    '<th>Likidite etkisi</th>': '<th>Liquidity impact</th>',

    # Executive overview
    'HEALTHY: "Sağlıklı"': 'HEALTHY: "Healthy"',
    'WATCH: "İzle"': 'WATCH: "Watch"',
    'ACTION_REQUIRED: "Aksiyon gerekli"': 'ACTION_REQUIRED: "Action required"',
    'CRITICAL: "Kritik"': 'CRITICAL: "Critical"',
    'LIQUIDITY: "Likidite"': 'LIQUIDITY: "Liquidity"',
    'STRESS: "Stres dayanımı"': 'STRESS: "Stress resilience"',
    'MATURITY: "Vade uyumu"': 'MATURITY: "Maturity profile"',
    'FUNDING: "Fonlama"': 'FUNDING: "Funding"',
    'RATE: "Faiz riski"': 'RATE: "Interest-rate risk"',
    'DATA: "Veri kapsamı"': 'DATA: "Data coverage"',
    'Acil ALM aksiyonu gerekiyor.': 'Immediate ALM action is required.',
    '12 aylık ALM profili yönetim aksiyonu gerektiriyor.': 'The 12-month ALM profile requires management action.',
    'Pozisyon fonlanmış durumda; temel risk limitleri izlenmeli.': 'The position is funded, but key risk limits require monitoring.',
    'ALM pozisyonu modellenen politika aralığında.': 'The ALM position remains within the modeled policy range.',
    '"Belirgin risk yok"': '"No dominant risk"',
    'Yönetim değerlendirmesi': 'Management assessment',
    ' aksiyon alanı · Baskın risk: ': ' action areas · Dominant risk: ',
    'Kullanılabilir likidite': 'Available liquidity',
    'Minimum ': 'Minimum ',
    ' vadesi geliyor': ' due within 12M',
    '+200 bp faiz etkisi': '+200 bp rate impact',
    '12 aylık vade görünümü': '12-month maturity view',
    'Kümülatif Maturity Gap': 'Cumulative Maturity Gap',
    '12A varlık': '12M assets',
    '12A yükümlülük': '12M liabilities',
    '36 aylık görünüm': '36-month view',
    'Faiz yapısı': 'Rate structure',
    'Repricing Profili': 'Repricing Profile',
    ' değişken': ' floating',
    'Son tarih: ': 'Due: ',
    'Funding plan detayına git →': 'View funding-plan details →',
    '90 günlük dayanım': '90-day resilience',
    'Stres Matrisi': 'Stress Matrix',
    '<span>Senaryo</span>': '<span>Scenario</span>',
    '<span>Minimum nakit</span>': '<span>Minimum cash</span>',
    '<span>Fonlama</span>': '<span>Funding</span>',
    '<span>İhlal</span>': '<span>Breach</span>',
    'Fonlama kaynakları': 'Funding sources',
    'Veri kapsamı: ': 'Data coverage: ',
    ' bulgu açıklanmayı bekliyor. Veri &amp; Girdiler barından kaynak kayıtları güncelleyebilirsiniz.': ' findings require review. Source records can be updated from the Data &amp; Inputs bar.',

    # Dashboard / navigation / errors
    'Analitik çalışma alanı': 'Analytical workspace',
    'Detay Analizler': 'Detailed Analyses',
    'Yönetim özetindeki risk ve aksiyonların hesaplama katmanları': 'Calculation layers behind the risks and actions in the executive overview',
    '90 günlük görünüm': '90-day view',
    'Likidite ve stres senaryoları': 'Liquidity & Stress Scenarios',
    'Grafikte bir güne tıklayarak o günün Gap Drivers analizini açın.': 'Click a date on the chart to open its Gap Drivers analysis.',
    'Seçili günün sürücüleri yenileniyor…': 'Refreshing selected-day drivers…',
    'En az bir güncel CSV veya manuel ALM pozisyonu ekleyin; alternatif olarak demo veriyi açın.': 'Add at least one current CSV or manual ALM position, or open the demo data.',
    'CFO analizi oluşturulamadı.': 'CFO analysis could not be generated.',
    ' örnek dosyası alınamadı.': ' sample file could not be loaded.',
    'Corporate ALM Intelligence ana sayfa': 'Corporate ALM Intelligence home',
    'Ana navigasyon': 'Main navigation',
    'Genel Bakış': 'Overview',
    '>Genel<': '>Overview<',
    'Veri ve Girdiler': 'Data & Inputs',
    '>Veri<': '>Data<',
    'Likidite': 'Liquidity',
    '>Vade<': '>Maturity<',
    'Fonlama': 'Funding',
    '>Faiz<': '>Rates<',
    'ALM bölümleri': 'ALM sections',
    'Konsolide': 'Consolidated',
    'Veri ve manuel ALM girdileri': 'Data and manual ALM inputs',
    'ALM görünümünün kısa vadeli likidite katmanı': 'Short-term liquidity layer of the ALM view',
    'CSV dosyalarınızı yükleyin, örnek dosyalarla gerçek pipeline’ı çalıştırın veya arayüzü görmek için demo veriyi açın.': 'Upload CSV files, run the real pipeline with sample files, or open the demo data to explore the interface.',
    'Demo cockpit’i aç': 'Open demo cockpit',

    # ALM positions panel
    'Pozisyonlar yüklenemedi.': 'Positions could not be loaded.',
    'Pozisyon kaydedilemedi.': 'Position could not be saved.',
    'Pozisyon silinemedi.': 'Position could not be deleted.',
    'Nakit ve kredi limitleri': 'Cash & Credit Facilities',
    'Banka pozisyonlarını manuel\n            girin; analiz parametreleri\n            otomatik güncellensin.': 'Enter bank positions manually; analysis parameters update automatically.',
    ' pozisyon': ' positions',
    'Kullanılabilir nakit': 'Available cash',
    'Kısıtlı nakit': 'Restricted cash',
    'Kalan limit': 'Available facilities',
    'Toplam likidite': 'Total liquidity',
    'Yeni manuel pozisyon ekle': 'Add manual position',
    'Pozisyon tipi': 'Position type',
    'Nakit hesabı': 'Cash account',
    'Kredi limiti': 'Credit facility',
    'Şirket / entity': 'Company / entity',
    '"Banka"': '"Bank"',
    '"Kredi veren"': '"Lender"',
    'Hesap ID': 'Account ID',
    'Kullanılabilir (mn)': 'Available (mn)',
    'Kısıtlı (mn)': 'Restricted (mn)',
    'Taahhütlü limit (mn)': 'Committed facility (mn)',
    'Kullanılan limit (mn)': 'Drawn facility (mn)',
    'Vade': 'Maturity',
    'Faiz tipi': 'Rate type',
    'Yıllık faiz (%)': 'Annual interest rate (%)',
    'Kaydediliyor…': 'Saving…',
    'Pozisyonu kaydet': 'Save position',
    '"NAKİT"': '"CASH"',
    '"LİMİT"': '"FACILITY"',
    'kullanılabilir': 'available',
    ' pozisyonunu sil': ' position',
    '>Sil<': '>Delete<',

    # Demo maturity labels / README residual UI names
    '"Vadesi geçmiş"': '"Overdue"',
    '"0–30 gün"': '"0–30 days"',
    '"331–365 gün"': '"331–365 days"',
    '`${index * 30 + 1}–${(index + 1) * 30} gün`': '`${index * 30 + 1}–${(index + 1) * 30} days`',
    '">12 ay"': '">12 months"',
    '">36 ay"': '">36 months"',
    '`${(index - 1) * 3}–${index * 3} ay`': '`${(index - 1) * 3}–${index * 3} months`',
    '**Demo veriyi yükle**': '**Load demo data**',
    '**Örnek CSV’lerle çalıştır**': '**Run with sample CSVs**',
    'The **Nakit ve kredi limitleri** panel': 'The **Cash & Credit Facilities** panel',
}

# These are legitimate proper names that may remain in demo data.
ALLOWED_TURKISH_LINES = (
    "Anadolu Bankası",
)


def translate_file(path: Path) -> None:
    if not path.exists():
        print(f"SKIP: {path} not found")
        return

    text = path.read_text(encoding="utf-8")
    original = text

    # Longest phrases first to avoid partial replacements corrupting a longer one.
    for source, target in sorted(REPLACEMENTS.items(), key=lambda item: len(item[0]), reverse=True):
        text = text.replace(source, target)

    if text != original:
        path.write_text(text, encoding="utf-8")
        print(f"UPDATED: {path}")
    else:
        print(f"UNCHANGED: {path}")


def report_remaining_turkish() -> None:
    pattern = re.compile(r"[çğıöşüÇĞİÖŞÜ]")
    print("\nPotential Turkish text remaining:\n")
    found = False
    for path in FILES:
        if not path.exists():
            continue
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            if pattern.search(line) and not any(allowed in line for allowed in ALLOWED_TURKISH_LINES):
                found = True
                print(f"{path}:{lineno}: {line.strip()}")
    if not found:
        print("None found (excluding allowed demo proper names).")


if __name__ == "__main__":
    for file_path in FILES:
        translate_file(file_path)
    report_remaining_turkish()
